operations_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('patients.urls')) # patients URLs
]

patients/urls.py
from django.urls import path

from patients.views import (
	PatientCreateView,
	PatientUpdateView,
	PatientDeleteView,
	PatientListView
)

app_name = 'patients'

urlpatterns = [
	path('', PatientListView.as_view(), name='index'), # index
	path('patients/create/', PatientCreateView.as_view(), name='create'), # patient create view
	path('patients/<int:id>/update/', PatientUpdateView.as_view(), name='update'), # patient update view
	path('patients/<int:id>/delete/', PatientDeleteView.as_view(), name='delete'), # patient delete
	path('patients/', PatientListView.as_view(), name='list'), # patient list
]

patients/models.py
from django.db import models


class Patient(models.Model):

    class GENDER(models.TextChoices):
        MALE = 'M', 'Male'
        FEMALE = 'F', 'Female'

    first_name = models.CharField(max_length=255, blank=False)
    last_name = models.CharField(max_length=255, blank=False)
    gender = models.CharField(max_length=10, choices=GENDER.choices, blank=True)
    age = models.PositiveIntegerField(blank=False)
    disease = models.TextField()
    doctor_name = models.CharField(max_length=255)
    doctor_fees = models.PositiveIntegerField(default=500)
    started_meds_on = models.DateField(null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_full_name(self):
        return f'{self.first_name} {self.last_name}'

    def get_gender(self):
        if self.gender == 'M':
            return 'Male'
        elif self.gender == 'F':
            return 'Female'
        else:
            return 'N/A'

patients/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from patients.models import Patient
from patients.utils import DateInput


class PatientForm(forms.ModelForm):

    started_meds_on = forms.DateField(required=False, widget=DateInput)

    class Meta:
        model = Patient
        exclude = [
            'date',
            'updated'
        ]
        labels = {
            'first_name': _('First name'),
            'last_name': _('Last name'),
            'gender': _('Gender'),
            'age': _('Age'),
            'doctor_name': _('Doctor'),
            'doctor_fees': _('Doctor Fees'),
            'started_meds_on': _('Started Meds On')
        }
        help_texts = {
            'started_meds_on': _('When you started taking you meds (if any)')
        }
        widgets = {
            'gender': forms.Select(attrs={
                'class': 'appearance-none',
                'placeholder': 'Select your gender'
            }),
            'doctor_fees': forms.NumberInput(attrs={
                'value': '500'
            })
        }

patients/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View
from django.forms.models import model_to_dict

from patients.models import Patient
from patients.forms import PatientForm


class PatientCreateView(View):

    template_name = 'patients/patient-create.html'

    def get(self, request):
        patient_form = PatientForm()
        context = {
            'patient_form': patient_form,
            'patients': self.get_queryset()
        }

        return render(request, self.template_name, context)

    def post(self, request):
        patient_form = PatientForm(request.POST)
        context = {
            'patient_form': patient_form,
            'patients': self.get_queryset()
        }

        if patient_form.is_valid():
            patient_form.save()

            return redirect('patients:create')

        patient_form = PatientForm()

        return render(request, self.template_name, context)

    def get_queryset(self):
        return Patient.objects.order_by('-updated')


class PatientUpdateView(View):

    template_name = 'patients/patient-update.html'

    def get(self, request, id):
        patient = get_object_or_404(Patient, id=id)
        patient_update_form = PatientForm(
            instance=patient,
            initial=model_to_dict(patient)
        )

        context = {
            'patient': patient,
            'patient_form': patient_update_form
        }

        return render(request, self.template_name, context)

    def post(self, request, id):
        patient = get_object_or_404(Patient, id=id)
        patient_update_form = PatientForm(
            request.POST,
            instance=patient,
            initial=model_to_dict(patient)
        )

        if patient_update_form.is_valid():
            patient_update_form.save()

            return redirect('patient:list')

        context = {
            'patient': patient,
            'patient_form': patient_update_form
        }

        return render(request, self.template_name, context)


class PatientDeleteView(View):

    def get(self, request, id):
        patient = get_object_or_404(Patient, id=id)
        patient.delete()

        return redirect('patients:list')


class PatientListView(View):

    template_name = 'patients/patient-list.html'

    def get(self, request):
        context = {
            'patients': self.get_queryset()
        }

        return render(request, self.template_name, context)

    def get_queryset(self):
        return Patient.objects.order_by('-updated')

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>
		{% block title %}
		{% endblock title %}
	</title>

	{% load static %}

	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	{% block styles %}
	{% endblock styles %}
</head>
<body>
	<nav class="w-full p-2 bg-gray-900 sticky top-0">
		<div class="container mx-auto grid grid-cols-6 gap-4">
			<div class="col-start-1 col-end-3">
				<button class="p-1 px-2 md:font-bold">
					<a class="text-white" href="#">Operations</a>
				</button>
			</div>

			<div class="col-end-8 col-span-1">
				<button class="p-1 px-2 bg-gray-800 rounded-md hover:bg-gray-700 transition duration-500">
					<a href="{% url "patients:list" %}" class="text-white">Patients</a>
				</button>

				<button class="p-1 px-2 bg-gray-800 rounded-md hover:bg-gray-700 transition duration-500">
					<a href="{% url "patients:create" %}" class="text-white">Add Patients</a>
				</button>
			</div>
		</div>
	</nav>

	<div class="container mx-auto px-2">
		{% block body %}
		{% endblock body %}
	</div>

	{% block scripts %}
	{% endblock scripts %}
</body>
</html>

templates/patients/components/patients-actions.html
<div>
	<a href="{% url "patients:update" patient.id %}">
	    <button class="my-1 md:my-0 p-2 py-1 text-white bg-blue-700 rounded">Update</button>
	</a>
	<a href="{% url "patients:delete" patient.id %}">
	    <button class="my-1 md:my-0 p-2 py-1 text-white bg-red-700 rounded">Delete</button>
	</a>
</div>

templates/patients/components/patients-update-form.html
<form class="grid grid-rows-1 gap-2" method="POST">
	{% csrf_token %}

	{% for field in patient_form %}
		<label>
			{{ field.label }}
		</label>
		{% if field.help_text %}
			<small><i>{{ field.help_text }}</i></small>
		{% endif %}
		{{ field }}
	{% endfor %}

	<div class="grid grid-cols-1 gap-2 py-2">
		<button class="bg-blue-700 text-white py-2" type="submit">Update</button>
	</div>
</form>

templates/patients/components/patients.html
{% load humanize %}

<div class="border-2 border-solid border-gray-200 my-2 rounded">
	<div class="p-2">
		{{ patient.get_full_name }}
	</div>

	<div class="p-2">
		<label class="text-gray-500">
			{{ patient.updated|naturaltime }}
		</label>
	</div>

	<div class="p-2 bg-gray-200">
		{% include 'patients/components/patients-actions.html' %}
	</div>
</div>

templates/patients/patient-create.html
{% extends "base.html" %}

{% block title %}
    Operations | Create Patients
{% endblock title %}

{% load static %}

{% block body %}
    <div class="grid grid grid-cols-1 gap-1 md:grid-cols-2 md:gap-2">
    	<div class="py-4">
	    	<div class="card">
	    		<div class="card-header bg-gray-200">
	    			<p class="font-bold">Create patient</p>
	    		</div>

	    		<div class="card-content">
			    	<form class="grid grid-rows-1 gap-2" method="POST">
			    		{% csrf_token %}

			    		{% for field in patient_form %}
			    			<label>
			    				{{ field.label }}
			    			</label>
			    			{% if field.help_text %}
			    				<small><i>{{ field.help_text }}</i></small>
		    				{% endif %}
			    			{{ field }}
			    		{% endfor %}

			    		<div class="grid grid-cols-1 gap-2 py-2">
			    			<button class="bg-blue-700 text-white py-2" type="submit">Submit</button>
			    		</div>
			    	</form>
	    		</div>
		    </div>
		</div>

    	<div class="py-4">
    		<div class="card">
    			<div class="card-content">
    				{% if patients %}
	    				{% for patient in patients %}					
				    		{% include 'patients/components/patients.html' %}
	    				{% endfor %}
			    	{% else %}
			    	    <label class="text-gray-400">
			    	    	No Patients yet
			    	    </label>
    				{% endif %}
    			</div>
    		</div>
    	</div>
    </div>
{% endblock body %}

templates/patients/patient-list.html
{% extends "base.html" %}

{% load humanize %}

{% block title %}
    Operations | Patients Lists
{% endblock title %}

{% block body %}
    <div class="p-4">
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Full name</th>
                    <th>Gender</th>
                    <th>Last updated</th>
                    <th cols="2">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for patient in patients %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ patient.get_full_name }}</td>
                        <td>{{ patient.get_gender }} </td>
                        <td>{{ patient.updated|naturaltime }}</td>
                        <td cols="2">
                            {% include 'patients/components/patients-actions.html' %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock body %}

templates/patients/patient-update.html
{% extends "base.html" %}

{% block title %}
    Operations | Patient Update | {{ patient.get_full_name }}
{% endblock title %}

{% block body %}
    <div class="py-4">
        {% include 'patients/components/patients-update-form.html' %}
    </div>
{% endblock body %}